### ISSUE TITLE
"Edit" link should be visible on existing articles

### ISSUE THREAD

**Issue by RemyPorter** [tdwtf/WtfWebApp#129]
When an administrator views a "Published" article, there's no edit link. Administrators should always be able to see that link.

Correction: the appearance of the edit link seems to be inconsistent. Sometimes it's there, sometimes it's not.

**Comment by apapadimoulis** [comment]
Are you sure about that? I’ve been able to view/edit before…

It’s done thru some weird cookie hack…

**Comment by RemyPorter** [comment]
I can do it if I dig through the admin interface and find the article, but if I'm looking at an article's page, there's no easy way to edit it.
![picture 2015-04-05 at 8 19 01 am](https://cloud.githubusercontent.com/assets/5325/6996798/8f71b4ee-db6c-11e4-82fe-f319d28de72b.PNG)

**Comment by RemyPorter** [comment]
Of course, as I was digging through the archives, I did see the link show up from time to time. So this may be honestly a bug, and not an enhancement- it should ALWAYS appear.

**Comment by apapadimoulis** [comment]
I think I figured it out…

https://github.com/tdwtf/WtfWebApp/blob/master/TheDailyWtf/Views/Articles/ViewArticle.cshtml#L18

https://github.com/tdwtf/WtfWebApp/blob/master/TheDailyWtf/Scripts/custom.js

https://github.com/tdwtf/WtfWebApp/blob/master/TheDailyWtf/Controllers/AdminController.cs#L76

… the IS_ADMin cookie is timing out? Maybe the work-around could be to visit the admin page again.

**Comment by RemyPorter** [comment]
Ah, that is it. I forget that that cookie times out super-fast.
