### ISSUE TITLE
Bug: comments sections for old articles show HTML tags everywhere, rendering them unreadable

### ISSUE THREAD

**Issue by xaroth8088** [tdwtf/WtfWebApp#130]
Example:
http://thedailywtf.com/articles/comments/If__0x2b__0x2b__Increments__0x2e__0x2e__0x2e_

Comments on this article appear to have double-escaped the HTML output, leading to some pretty unreadable content.

**Comment by BenLubar** [comment]
should be completely fixed by the next deploy
