### ISSUE TITLE
Sidebar WTF is empty

### ISSUE THREAD

**Issue by aapis** [tdwtf/WtfWebApp#131]
Sometimes a refresh fixes it, sometimes it doesn't.  Tested with an adblocker running and without, list is empty either way so I assume it's a data issue.

https://www.dropbox.com/s/hgtjduyber93oaz/Screenshot%202015-04-17%2011.42.37.png?dl=0

**Comment by apapadimoulis** [comment]
That stuff is pulled from Discourse, so I think it’s whenever th e API goes down.

**Comment by BenLubar** [comment]
Handled in the tdwtf-crp branch:

https://github.com/tdwtf/WtfWebApp/commit/730d1258b01d5161e0d5a4e9c30b8a4c3c459025#diff-b8742416f17fa2f09b20390abcc03bb1R69
