### ISSUE TITLE
Main menu delay

### ISSUE THREAD

**Issue by alisonken1** [tdwtf/WtfWebApp#132]
It would be helpful if the main menu along the top (FEATURE ARTICLES, CODESOD, ERROR'D, FORUMS, OTHER ARTICLES) would have a delay (3-5 seconds).

It's hard to work with tabs in the browser when every time I switch back to the DWTF tab to have the menu cover the article I'm trying to read.

**Comment by aapis** [comment]
Might be a bit late but I have to disagree with this, adding delays to basic web functionality like this is terrible for UX.  People would think it's broken at 3-5 seconds, no one expects delays when hovering over/off a dropdown menu.  I think the most you could get away with a few hundred milliseconds, but it's still not a good idea.
