### ISSUE TITLE
API Suggestions - Lists of series and a Since end point

### ISSUE THREAD

**Issue by magnus-eriksson** [tdwtf/WtfWebApp#140]
I'm thinking of buildning a TDWTF-app for Windows 10 mobile (yes, you heard me!). There is an endpoint where you can fetch articles per series but there's no endpoint to get a list of the available series.

It would also be good to have a "since" filter on fetching articles (either date or since a specific ID) to be able to only fetch new articles.

is it possible to get those? The series-list is the one that's most interesting, though.

**Comment by pikle6** [comment]
1. I agree with the series-list end point. I will go through the code to see if that's doable and update soon.

2. I really wanted to add the 'since' feature in my initial commit. But I couldn't find the time to add it in. Let me give this one a shot too.

**Comment by pikle6** [comment]
https://github.com/tdwtf/WtfWebApp/pull/148
