### ISSUE TITLE
First run error

### ISSUE THREAD

**Issue by aapis** [tdwtf/WtfWebApp#144]
![tdwtferror](https://cloud.githubusercontent.com/assets/899633/12436616/22da8b0c-bed4-11e5-8688-da9a03fdc66a.png)

I'm running into this issue while building/running the project.  All I've done is checkout the project and build the project.  Again, I'm not really a C# guy (though I am using this project as a learning experience), so I may be doing something obviously wrong.

**Comment by apapadimoulis** [comment]
The ads most not be loaded/configured locally. IDK how to do that off hand, but likely the GuidsByOriginalUrl is what's returning null .... or maybe it's adsRedirects is already null. Anyway, just replace the two `.` with `?.` and hope that works :)

**Comment by aapis** [comment]
That did the trick.  Thanks!
