### ISSUE TITLE
Date formating

### ISSUE THREAD

**Issue by remygrandin** [tdwtf/WtfWebApp#155]
With the new version of TRWTF website, i've notice a change in date format, it's now in the (illogical) english format. If I remeber well, it was previously on a yyyy-MM-dd format

Would it be possible to either :

 - Put back the old and more standard notation
 - Give us an option to switch it
 - Or even better, doing the formating according to the user culture

Thanks for considering this issue/improvement

**Comment by apapadimoulis** [comment]
Despite the date being in the ****correct**** ('MURICAN) format, until the rest of the world sees the light, and adapts to the right way of doing things, we should do `yyyy-MM-dd `!

**Comment by remygrandin** [comment]
Iso for the win ^^
