### ISSUE TITLE
Cannot view Community Server attachments in articles

### ISSUE THREAD

**Issue by TwelveBaud** [tdwtf/WtfWebApp#159]
The fix in #113 seems to have bitrotted, as many a [Pop-up Potpourri](http://thedailywtf.com/articles/Pop-up_Potpourri_0x3a__Arcade_Edition) can attest. It looks like it's only allowing it through if the CS post ID corresponds to a live article, not if it's for example an arbitrary Sidebar post.

Prepending "forums." or "what." to the domain seems to recover the original images, so it's just the route that needs fixing.

**Comment by BenLubar** [comment]
Looks like it's unrelated to #113.
