### ISSUE TITLE
Previewing Unpublished Article in Draft or Pending Status = HTTP 500

### ISSUE THREAD

**Issue by mbowytz** [tdwtf/WtfWebApp#162]
Go to the Admin Page, create an article, save it and then click on the "Preview" link. You'll get the standard TDWTF custom HTTP 500 page stating "An error occurred while processing the request. If this error continues, please reach out to an Administrator using the contact form."

Only way to actually preview is to set the article to Published status at some point in the future.

**Comment by BenLubar** [comment]
@apapadimoulis I thought we fixed this one. Did we deploy?

**Comment by apapadimoulis** [comment]
I thought we did!

**Comment by BenLubar** [comment]
The fix should be deployed now. (See #163)
