### ISSUE TITLE
500 Error on a specific article

### ISSUE THREAD

**Issue by RemyPorter** [tdwtf/WtfWebApp#163]
Submitted by a reader:
The article <http://thedailywtf.com/articles/Hastening-an-Inevitable> does not load, causing a 500 error. Additionally, attempting to submit the contact form caused another 500 error.

**Comment by BenLubar** [comment]
@apapadimoulis was the fix for `<snip>` deployed?

https://github.com/tdwtf/WtfWebApp/commit/f9a9b06f29ece835f6d900d9b5d7045c9ba3f4e0

**Comment by apapadimoulis** [comment]
Maybe not; pushing a new version out now!

**Comment by BenLubar** [comment]
Looks to be fixed with that patch. Closing.
