### ISSUE TITLE
Unable to Complete the Edit of an Article

### ISSUE THREAD

**Issue by RemyPorter** [tdwtf/WtfWebApp#170]
As of TODAY (9/5), I'm unable to edit articles. This was working fine YESTERDAY (9/4).

When I edit an article, and click "Save", the browser starts attempting to load, but *nothing* actually happens. Eventually it times out and reloads the same screen, without the "Published" option is the "Status" field. The article has not been saved. This is happening to both newly created articles and already existing articles.

This COMPLETELY breaks article posting, which is a bit of a problem.

**Comment by BenLubar** [comment]
I can't reproduce it locally, so it must be a problem with something specific to the production server.

**Comment by RemyPorter** [comment]
This did clear up. Should have closed this weeks ago.
