### ISSUE TITLE
Article image placement is wonky

### ISSUE THREAD

**Issue by XaserAcheron** [tdwtf/WtfWebApp#171]
Perodically, the "flavor image" placement in the article body causes awkward segments of whitespace, and it's been something I've been meaning to bring up for a bit. [Today's article](http://thedailywtf.com/articles/the-contractor) takes the cake, though.

![2016-10-20 09_18_57-the contractor - the daily wtf](https://cloud.githubusercontent.com/assets/4601589/19579571/07698512-96e7-11e6-9ebe-39f22d022730.png)

"Where else do we put it?" is a pretty subjective question, no doubt, but I'm certain the answer is some variant of _"anything but that"_. :P

**Comment by aapis** [comment]
Not sure if it's a bug, seems like just a poor image choice.  Maybe editors should have a note somewhere that "featured images" (or whatever the CMS calls them) must be at least 300px wide or something?

**Comment by XaserAcheron** [comment]
I'm not convinced it's just the size. The placement of the image in the article seems to have a profound effect on the formatting -- Sometimes smaller images [work just fine](http://thedailywtf.com/articles/fully-wireless), and images [being too large](http://thedailywtf.com/articles/logjam) is a thing too.

Some other examples of strange formatting on recent-ish pages:
http://thedailywtf.com/articles/red-black-trees
http://thedailywtf.com/articles/every-possible-case (notice the code-collapse being oddly narrow)
http://thedailywtf.com/articles/it-takes-one-function

CSS is evil, so I feel a bit Pandora-ish here. The mythical person, of course, not the streaming service. :P

**Comment by aapis** [comment]
The problem seems to be the styling associated with the `.inset` selector.  In the example where you show it working, that image is not wrapped by an `.inset` element so that might explain why it works fine.  If there is a code fix here, maybe it's just to stop adding the `inset` class to the featured image?

**Comment by BenLubar** [comment]
The CSS has a comment right before the .inset definition:

```
/*Left over classes still in use from first CSS revision, kept to keep archival articles current*/
.inset {
  float: right;
  margin: 8pt;
  width: 52%;
}
```

Which means it's deprecated and should not be used.

**Comment by XaserAcheron** [comment]
Hmm, that's part of it, looks like. For the "good" images, there's a chunk of inline styling (`style="float:right; padding-left:10px; padding-bottom:10px;"`) on a `<p>` wrapper around the image that's necessary. Taking off `.inset` and plunking in the inline style fixes it for the originally-reported article. Though I must ask: is this inline style defined somewhere in-code (i.e. is "standard") or are authors just plunking it in where they need it?

Still doesn't do anything for "It Takes One Function" or "Every Possible Case" (heh), but these are different (edge?) cases. And the gigantic "XML" image is certainly a case of "do better, author." Nobody needs to see that. :P

**Comment by patrickwroach** [comment]
I went ahead an made a minor adjustment to the inset class.  Ben is right, it's mostly meant to be depreciated and is kept around for the tons of archived articles that used it.  
That said, if current authors are using it, might as well make it work at least as well as it can.  

Here is what changed: 
Inset width decreased from 52% to 35%
Images/text centered

As this isn't a rush, we will build this to the live site sometime in the next couple of days alongside other needs. Hope this helps folks, let me know if there are other changes needed.  
https://github.com/tdwtf/WtfWebApp/commit/f7efa6de14295e58cab4d84bd5248b3e383d0046

**Comment by XaserAcheron** [comment]
Heh, forgot I'd file this until I got a GH notification on the closure. Either way, the articles in question look way better now.Thanks for the fixins!
