### ISSUE TITLE
Invalid CssClass on the /series endpoint?

### ISSUE THREAD

**Issue by magnus-eriksson** [tdwtf/WtfWebApp#193]
It seems like the `/series` endpoint returns some strange values for the property `CssClass`.

All series has the same `"CssClass": "soapbox"` except the series `Alex's Soapbox` which has `"CssClass": "tales"`.

**Comment by BenLubar** [comment]
here's where CssClass is defined: https://github.com/tdwtf/WtfWebApp/blob/547a567fafd6529c50d9995ad52af8dda595741b/TheDailyWtf/Models/SeriesModel.cs#L28-L41
