### ISSUE TITLE
Dropdown menus flow off the bottom of the screen

### ISSUE THREAD

**Issue by thebecwar** [tdwtf/WtfWebApp#44]
Screenshot:
![trwtf part 2](https://cloud.githubusercontent.com/assets/4549675/4688361/da5c3e5e-5672-11e4-8313-bdb6d5cee3a4.png)

Win 7, Firefox 32, 1600x900 (max for the display)

Not sure the menu items really need all that vertical padding.

**Comment by patrickwroach** [comment]
Fixed in recent version
