### ISSUE TITLE
Double Encoded Article Titles

### ISSUE THREAD

**Issue by apxltd** [tdwtf/WtfWebApp#54]
I'm not sure how many articles are like this one: \* fix html titles http://thedailywtf.com/articles/Classic_WTF_-_And_I_think_I_0x27_ll_call_it__0x2e__0x2e__0x2e__0x2e___0x26_quot_0x3b_Referential_Integrity_0x26_quot_0x3b__! --- but, we should either rhandle with a datafix or by only htmlencoding article titles after a certain date.

**Comment by BenLubar** [comment]
The article is here: <http://thedailywtf.com/articles/And_I_think_I_0x27_ll_call_it__0x2e__0x2e__0x2e__0x2e___0x22_Referential_Integrity_0x22__!>

The article it links to is located here: <http://thedailywtf.com/articles/tblStaffDirectory>. However, clicking the link in the article gives a 404 (uninclused) error. According to the internet archive, it redirected properly at some point in 2009, but it doesn't now.
