### ISSUE TITLE
Article titles not clickable in IE 9

### ISSUE THREAD

**Issue by jfredrickson** [tdwtf/WtfWebApp#76]
In IE 9, hovering over the article titles on the main page turns the mouse cursor into a text insertion cursor, and clicking does nothing. However, the white space to the right and underneath the title is clickable and leads to the article page.

In this screenshot, the circled area is clickable:
![capture](https://cloud.githubusercontent.com/assets/171487/4705485/41b087e4-587c-11e4-9194-4a9150db369c.PNG)

**Comment by patrickwroach** [comment]
Closing, fixed on new site
